//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.30 at 05:59:42 PM ALMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soap.roland.com/dto/accounts", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.roland.soap.dto.accounts;
